M48
; DRILL file {KiCad 8.0.8} date 2025-03-16T18:36:02-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-16T18:36:02-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X146.92Y-116.0
X157.08Y-116.0
X168.88Y-116.08
X179.04Y-116.08
T2
X152.0Y-116.0
X173.96Y-116.08
M30
